<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vcl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>VCL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(acl)\b</string>
			<key>name</key>
			<string>keyword.other.vcl.acl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(backend)\s+([a-zA-Z0-9_]+)\s*{</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.backend.vcl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.backed.vcl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.backend.vcl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#backend-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted-string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(sub)\s+([a-zA-Z0-9_]+)\s*{</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.sub.vcl.action</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.vcl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.sub.vcl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sub-body</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(director|probe|import)\b</string>
			<key>name</key>
			<string>keyword.other.vcl</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>backend-definition</key>
		<dict>
			<key>match</key>
			<string>\b(host|port)\b</string>
			<key>name</key>
			<string>support.other.backend.vcl</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.vcl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(#).*$\n?</string>
					<key>name</key>
					<string>comment.line.vcl</string>
				</dict>
			</array>
		</dict>
		<key>function-invocation</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.vcl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\S+)\((.*)\)</string>
			<key>name</key>
			<string>meta.control.function</string>
		</dict>
		<key>quoted-string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.vcl</string>
		</dict>
		<key>sub-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s(call|hash_data|panic|ban|ban_url|remove|return|rollback|set|synthetic|unset|purge|error)\b</string>
					<key>name</key>
					<string>keyword.control.vcl.action</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(if|elseif)\s*\((.+)\)\s*{</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.vcl.if</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.control.vcl.if</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sub-body</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(else)\s*{</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.vcl.else</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.control.vcl.else</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sub-body</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(regsub|regsuball|true|false)\b(?![?!])</string>
					<key>name</key>
					<string>constant.language.vcl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted-string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.varnish.vcl</string>
	<key>uuid</key>
	<string>D03975D6-0E30-46EC-9A63-AE75EA409EB9</string>
</dict>
</plist>
